worker_processes 2;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;
    
    upstream server_cluster {
        least_conn;
        server app1:3000;
        server app2:3000;
        server app3:3000;
        server app4:3000;
        server app5:3000;
    }
    
    server {
        listen 80;
        server_name localhost;
        ssl_certificate /etc/nginx/certificates/nginx.crt;       # linux path
        ssl_certificate_key /etc/nginx/certificates/nginx.key;   # linux path
        location / {
            proxy_pass http://server_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}